### ISSUE TITLE
Crash: Channel and member update

### ISSUE THREAD

**Issue by Pan-i386** [maddinat0r/samp-discord-connector#37] opened 2017-11-08 14:32 UTC
Server crash when update channel on discord ( edit roles, placement )
* Easy solution: Enable/Disable settings for Update Callbacks.
DCC_DisableChannelCallbacks();
DCC_DisableUserCallbacks();
DCC_DisableGuildCallbacks();

**Comment by maddinat0r** [comment] 2017-11-08 17:07
Can you always reproduce your crash? Could you upload your `discord-connector.log` here?

**Comment by NicKv7** [comment] 2018-01-29 11:51
I had the same problem and temporarily disabled the plugin and script.

I'll be adding information soon. I'm just going to get everything that is needed, and it takes a while, because the plugin debug everything and let it work for a few days (+/- 160mb of logs).

**Comment by NicKv7** [comment] 2018-01-29 12:14
```
[27/01/2018 13:07:06] [plugins/discord-connector] Error while retrieving HTTP POST response from '/api/v6/channels/403293089961082882/messages': end of stream
[27/01/2018 14:09:53] [plugins/discord-connector] Error while retrieving HTTP POST response from '/api/v6/channels/403293089961082882/messages': end of stream

```

Can that mean something serious? I was in the error log.

**Comment by maddinat0r** [comment] 2018-01-29 15:31
It's not serious, you can ignore it for now.
Can you post the last 50 log lines of the discord connector log before the crash happened?

**Comment by NicKv7** [comment] 2018-01-29 15:35
```
[27/01/2018 12:23:10] [DEBUG] WebSocket::OnWsRead
[27/01/2018 12:23:10] [DEBUG] WebSocket::WsRead
[27/01/2018 12:23:20] [DEBUG] WebSocket::OnWsRead
[27/01/2018 12:23:20] [DEBUG] WebSocket::WsRead
[27/01/2018 12:23:20] [DEBUG] PawnCallbackManager::Execute(name=DCC_OnGuildMemberUpdate,amx=0x97c0870, cb_idx=-10004, args_push_addr=-1)
[27/01/2018 12:23:20] [INFO] executing PAWN callback 'DCC_OnGuildMemberUpdate'...
[27/01/2018 12:23:20] [INFO] PAWN callback successfully executed.
[27/01/2018 12:23:30] [DEBUG] WebSocket::OnWsRead
[27/01/2018 12:23:30] [DEBUG] WebSocket::WsRead
[27/01/2018 12:23:30] [DEBUG] PawnCallbackManager::Execute(name=DCC_OnGuildMemberUpdate,amx=0x97c0870, cb_idx=-10004, args_push_addr=-1)
[27/01/2018 12:23:30] [INFO] executing PAWN callback 'DCC_OnGuildMemberUpdate'...
[27/01/2018 12:23:30] [INFO] PAWN callback successfully executed.
[27/01/2018 12:23:35] [DEBUG] WebSocket::OnWsRead
[27/01/2018 12:23:35] [DEBUG] WebSocket::WsRead
[27/01/2018 12:23:35] [DEBUG] PawnCallbackManager::Execute(name=DCC_OnChannelMessage,amx=0x97c0870, cb_idx=34, args_push_addr=12063788)
[27/01/2018 12:23:35] [INFO] executing PAWN callback 'DCC_OnChannelMessage'...
[27/01/2018 12:23:35] [INFO] PAWN callback successfully executed.
[27/01/2018 12:23:37] [DEBUG] WebSocket::OnWsRead
[27/01/2018 12:23:37] [DEBUG] WebSocket::WsRead
[27/01/2018 12:23:37] [DEBUG] PawnCallbackManager::Execute(name=DCC_OnChannelCreate,amx=0x97c0870, cb_idx=-10003, args_push_addr=-1)
[27/01/2018 12:23:37] [INFO] executing PAWN callback 'DCC_OnChannelCreate'...
[27/01/2018 12:23:37] [INFO] PAWN callback successfully executed.
[27/01/2018 12:23:46] [DEBUG] WebSocket::DoHeartbeat
[27/01/2018 12:23:46] [DEBUG] sending heartbeat
[27/01/2018 12:23:46] [DEBUG] WebSocket::OnWsRead
[27/01/2018 12:23:46] [DEBUG] heartbeat ACK
[27/01/2018 12:23:46] [DEBUG] WebSocket::WsRead
[27/01/2018 12:23:48] [DEBUG] WebSocket::OnWsRead
[27/01/2018 12:23:48] [DEBUG] WebSocket::WsRead
[27/01/2018 12:23:48] [DEBUG] PawnCallbackManager::Execute(name=DCC_OnGuildMemberUpdate,amx=0x97c0870, cb_idx=-10005, args_push_addr=-1)
[27/01/2018 12:23:48] [INFO] executing PAWN callback 'DCC_OnGuildMemberUpdate'...
[27/01/2018 12:23:48] [INFO] PAWN callback successfully executed.
[27/01/2018 12:23:50] [DEBUG] WebSocket::OnWsRead
[27/01/2018 12:23:53] [INFO] changed log level from 'warning, error' to 'debug, info, warning, error'
[27/01/2018 12:23:53] [DEBUG] Network::Initialize
[27/01/2018 12:23:53] [DEBUG] Http::Get
[27/01/2018 12:23:53] [DEBUG] Http::SendRequest
[27/01/2018 12:23:53] [DEBUG] Http::PrepareRequest
[27/01/2018 12:23:53] [DEBUG] Http::Connect
[27/01/2018 12:23:53] [DEBUG] WebSocket::Connect
[27/01/2018 12:23:53] [DEBUG] WebSocket::WsRead
[27/01/2018 12:23:53] [DEBUG] WebSocket::WsIdentify
[27/01/2018 12:23:53] [DEBUG] WebSocket::OnWsRead
[27/01/2018 12:23:53] [DEBUG] WebSocket::DoHeartbeat
[27/01/2018 12:23:53] [DEBUG] sending heartbeat
[27/01/2018 12:23:53] [DEBUG] WebSocket::WsRead
[27/01/2018 12:23:53] [DEBUG] WebSocket::OnWsRead
[27/01/2018 12:23:53] [DEBUG] heartbeat ACK
[27/01/2018 12:23:53] [DEBUG] WebSocket::WsRead
[27/01/2018 12:23:53] [DEBUG] WebSocket::OnWsRead
[27/01/2018 12:23:53] [DEBUG] WebSocket::WsRead
[27/01/2018 12:23:54] [DEBUG] WebSocket::OnWsRead
[27/01/2018 12:23:54] [DEBUG] WebSocket::WsRead
[27/01/2018 12:23:55] [DEBUG] DCC_FindChannelById("403293089961082882")
[27/01/2018 12:23:55] [DEBUG] DCC_FindChannelById: return value: '7'
[27/01/2018 12:23:55] [DEBUG] DCC_FindUserByName("Meguinha", "0407")
[27/01/2018 12:23:55] [DEBUG] DCC_FindUserByName: return value: '1'
[27/01/2018 12:23:55] [DEBUG] DCC_FindGuildById("242005830663143435")
[27/01/2018 12:23:55] [DEBUG] DCC_FindGuildById: return value: '1'
[27/01/2018 12:24:04] [DEBUG] WebSocket::OnWsRead
[27/01/2018 12:24:06] [INFO] changed log level from 'warning, error' to 'debug, info, warning, error'
[27/01/2018 12:24:06] [DEBUG] Network::Initialize
[27/01/2018 12:24:06] [DEBUG] Http::Get
[27/01/2018 12:24:06] [DEBUG] Http::SendRequest
[27/01/2018 12:24:06] [DEBUG] Http::PrepareRequest
[27/01/2018 12:24:06] [DEBUG] Http::Connect
[27/01/2018 12:24:06] [DEBUG] WebSocket::Connect
[27/01/2018 12:24:07] [DEBUG] WebSocket::WsRead
[27/01/2018 12:24:07] [DEBUG] WebSocket::WsIdentify
[27/01/2018 12:24:07] [DEBUG] WebSocket::OnWsRead
[27/01/2018 12:24:07] [DEBUG] WebSocket::DoHeartbeat
[27/01/2018 12:24:07] [DEBUG] sending heartbeat
[27/01/2018 12:24:07] [DEBUG] WebSocket::WsRead
[27/01/2018 12:24:07] [DEBUG] WebSocket::OnWsRead
[27/01/2018 12:24:07] [DEBUG] heartbeat ACK
[27/01/2018 12:24:07] [DEBUG] WebSocket::WsRead
[27/01/2018 12:24:07] [DEBUG] WebSocket::OnWsRead
[27/01/2018 12:24:07] [DEBUG] WebSocket::WsRead
[27/01/2018 12:24:07] [DEBUG] WebSocket::OnWsRead
[27/01/2018 12:24:07] [DEBUG] WebSocket::WsRead
[27/01/2018 12:24:08] [DEBUG] DCC_FindChannelById("403293089961082882")
[27/01/2018 12:24:08] [DEBUG] DCC_FindChannelById: return value: '7'
[27/01/2018 12:24:08] [DEBUG] DCC_FindUserByName("Meguinha", "0407")
[27/01/2018 12:24:08] [DEBUG] DCC_FindUserByName: return value: '1'
[27/01/2018 12:24:08] [DEBUG] DCC_FindGuildById("242005830663143435")
[27/01/2018 12:24:08] [DEBUG] DCC_FindGuildById: return value: '1'
[27/01/2018 12:24:14] [DEBUG] WebSocket::OnWsRead
[27/01/2018 12:24:14] [DEBUG] WebSocket::WsRead
[27/01/2018 12:24:14] [DEBUG] PawnCallbackManager::Execute(name=DCC_OnGuildMemberUpdate,amx=0x9ab3830, cb_idx=-10003, args_push_addr=-1)
[27/01/2018 12:24:14] [INFO] executing PAWN callback 'DCC_OnGuildMemberUpdate'...
[27/01/2018 12:24:14] [INFO] PAWN callback successfully executed.
[27/01/2018 12:24:15] [DEBUG] WebSocket::OnWsRead
[27/01/2018 12:24:15] [DEBUG] WebSocket::WsRead
[27/01/2018 12:24:15] [DEBUG] PawnCallbackManager::Execute(name=DCC_OnGuildMemberUpdate,amx=0x9ab3830, cb_idx=-10003, args_push_addr=-1)
[27/01/2018 12:24:15] [INFO] executing PAWN callback 'DCC_OnGuildMemberUpdate'...
[27/01/2018 12:24:15] [INFO] PAWN callback successfully executed.
[27/01/2018 12:24:20] [DEBUG] WebSocket::OnWsRead
[27/01/2018 12:24:20] [DEBUG] WebSocket::WsRead
[27/01/2018 12:24:20] [DEBUG] PawnCallbackManager::Execute(name=DCC_OnGuildMemberUpdate,amx=0x9ab3830, cb_idx=-10003, args_push_addr=-1)
[27/01/2018 12:24:20] [INFO] executing PAWN callback 'DCC_OnGuildMemberUpdate'...
[27/01/2018 12:24:20] [INFO] PAWN callback successfully executed.
[27/01/2018 12:24:25] [DEBUG] WebSocket::OnWsRead
[27/01/2018 12:24:25] [DEBUG] WebSocket::WsRead
[27/01/2018 12:24:43] [DEBUG] WebSocket::OnWsRead
[27/01/2018 12:24:43] [DEBUG] WebSocket::WsRead
[27/01/2018 12:24:43] [DEBUG] PawnCallbackManager::Execute(name=DCC_OnGuildMemberUpdate,amx=0x9ab3830, cb_idx=-10003, args_push_addr=-1)
[27/01/2018 12:24:43] [INFO] executing PAWN callback 'DCC_OnGuildMemberUpdate'...
[27/01/2018 12:24:43] [INFO] PAWN callback successfully executed.
[27/01/2018 12:24:46] [DEBUG] WebSocket::OnWsRead
[27/01/2018 12:24:46] [DEBUG] WebSocket::WsRead
[27/01/2018 12:24:47] [DEBUG] WebSocket::OnWsRead
[27/01/2018 12:24:47] [DEBUG] WebSocket::WsRead
[27/01/2018 12:24:47] [DEBUG] WebSocket::OnWsRead
[27/01/2018 12:24:47] [DEBUG] WebSocket::WsRead

```

**Comment by maddinat0r** [comment] 2018-01-29 15:40
Yes, this is very likely related to #43. I'll fix this as soon as I get some more free time.

**Comment by Sasuke-Uchiha** [comment] 2018-02-19 18:19
[discord-connector.log](https://github.com/maddinat0r/samp-discord-connector/files/1737837/discord-connector.log)
Same as report states crashed for the same reason.

**Comment by maddinat0r** [comment] 2018-03-04 15:40
I've just released v0.2.2 with a bug fix for this. Can you all please try it out and report back if that crash still occurs?

**Comment by NicKv7** [comment] 2018-03-04 22:07
I noticed that when I updated the plugin, I can not even get the name of the member who sent a message through discord.

**Comment by maddinat0r** [comment] 2018-03-05 20:48
@Sasuke-Uchiha I've now released v0.2.3 with various bug fixes. Can you try that one out please?

**Comment by NicKv7** [comment] 2018-03-06 01:18
I get some of these log errors.

[ERROR] invalid UTF-8 string: [json.exception.type_error.316] invalid UTF-8 byte at index 14: 0x61
[ERROR] can't update guild member presence: guild id "offline" not cached
[ERROR] can't update guild member presence: guild id "online" not cached

**Comment by maddinat0r** [comment] 2018-03-08 10:09
The first error suggests that you are passing an invalid UTF-8 string (likely to `DCC_SendChannelMessage`). Discord expects an UTF-8 string, so you have to provide a valid one if you are using special symbols.
The other two errors are due to a minor bug, which disables the `DCC_GetGuildMemberStatus` native function. This will be fixed soon.

**Comment by Sasuke-Uchiha** [comment] 2018-03-08 15:11
I think this issue can be locked now, as it's working thanks. The update is working good just tried, Was busy so didn't notice first. 

Anyways if something else comes up. I will open up a new issue.

**Comment by maddinat0r** [comment] 2018-03-09 08:23
Alright, good to hear that!

**Closed by maddinat0r** 2018-03-09 08:23 UTC
