### ISSUE TITLE
DCC_GetUserId: invalid user id '0'

### ISSUE THREAD

**Issue by Yousha** [maddinat0r/samp-discord-connector#82] opened 2018-10-12 20:19 UTC
> DCC_GetUserId: invalid user id '0' (..\include\utilities.inc:9574)

```
public DCC_OnChannelMessage(DCC_Channel:channel, DCC_User:author, const message[])
{
   new userId[MAX_STRING_DISCORDUSERID + 1];

   if (!DCC_GetUserId(DCC_User:author, userId)) // Line 9574
   {
      return 0;
   }

```

Why?

_Plugin version: 0.2.4
SAMP version: 0.3.7-R2
OS: Debian 64bit_

**Comment by maddinat0r** [comment] 2018-10-29 11:49
This error might be caused by #67, where some users were not cached by the plugin. As that one is fixed in the next update, try reproducing it when v0.3 is out.

**Comment by maddinat0r** [comment] 2019-05-06 23:20
Feel free to try a dev build from AppVeyor: https://ci.appveyor.com/project/maddinat0r/samp-discord-connector (select a successful build job with config = Release and image = Windows/Ubuntu (depending on whether you need a Windows or Linux build and click on artifacts)

**Closed** 2019-05-16 17:18 UTC
